# Generated by Django 4.0.5 on 2022-06-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ['-pk']},
        ),
    ]
