# Generated by Django 4.0.5 on 2022-06-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_alter_comment_options_alter_likes_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.AlterField(
            model_name='likes',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default='like', max_length=10),
        ),
    ]
